### Ping
GET http://localhost:3000 HTTP/1.1

### Who Am I
GET http://localhost:3000/whoami HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MWNhY2M4N2Q4OTM5ZDViYzE0MzU2YjQiLCJpYXQiOjE2NDA2ODA1ODh9.CzQWU-_LyYBEUJpnEVB716wWTawxMpacXbZphuGovwQ

### Login
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "hacker@gmail.com",
    "password": "123456"
}

### Register
POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "Hacker",
    "email": "hacker@gmail.com",
    "password": "123456"
}


### Get all all of your groups includes created by you.
GET http://localhost:3000/groups HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MWNhY2M4N2Q4OTM5ZDViYzE0MzU2YjQiLCJpYXQiOjE2NDA2ODA1ODh9.CzQWU-_LyYBEUJpnEVB716wWTawxMpacXbZphuGovwQ


### Get all groups created by you
GET http://localhost:3000/groups/me HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MWNhY2M4N2Q4OTM5ZDViYzE0MzU2YjQiLCJpYXQiOjE2NDA2ODA1ODh9.CzQWU-_LyYBEUJpnEVB716wWTawxMpacXbZphuGovwQ


### Make a group
POST http://localhost:3000/groups HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MWNhY2M4N2Q4OTM5ZDViYzE0MzU2YjQiLCJpYXQiOjE2NDA2ODA1ODh9.CzQWU-_LyYBEUJpnEVB716wWTawxMpacXbZphuGovwQ
Content-Type: application/json

{
    "name": "First Group"
}


### Find mambers to add in a group
GET http://localhost:3000/mambers/search/shanta HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MWNhY2M4N2Q4OTM5ZDViYzE0MzU2YjQiLCJpYXQiOjE2NDA2ODA1ODh9.CzQWU-_LyYBEUJpnEVB716wWTawxMpacXbZphuGovwQbhROvbQnt-xc2c


### Add mamber to a group
POST http://localhost:3000/groups/add HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MWNhY2M4N2Q4OTM5ZDViYzE0MzU2YjQiLCJpYXQiOjE2NDA2ODA1ODh9.CzQWU-_LyYBEUJpnEVB716wWTawxMpacXbZphuGovwQ
Content-Type: application/json

{
    "groupId": "61cb0b7acf77802015b59241",
    "userId": "61cb12098204c2223c2ffc61"
}


### get all mambers in a group
GET http://localhost:3000/groups/61cb0b7acf77802015b59241/mambers/ HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MWNhY2M4N2Q4OTM5ZDViYzE0MzU2YjQiLCJpYXQiOjE2NDA2ODA1ODh9.CzQWU-_LyYBEUJpnEVB716wWTawxMpacXbZphuGovwQ
